
package simpletableconnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Vinay
 */
public class UserBookshelf extends javax.swing.JFrame {

    /**
     * Creates new form UserBookshelf
     */

    	DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
	LocalDate localDate = LocalDate.now();
        
    Connection conn = null;

    public UserBookshelf() {
        initComponents();
        //DisplayTable();
    }
    public UserBookshelf(String para, int id, int quantity) {
        initComponents();
        user_fullName.setText(para);
        adminTxtIDLabel.setText(String.valueOf(id));
        quantityHolder.setText(String.valueOf(quantity));
        
        DisplayTable();
    }
    
    int count = 0;
    
    public Connection getConnection() {

        try {
            conn = DriverManager.getConnection("jdbc:mysql:///customerstuff","root","And98rew");
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        return conn;
    }

    
    private void DisplayTable() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql:///customerstuff","root","And98rew");
            String sql = "select * from book_info";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            jt_bookData.setModel(DbUtils.resultSetToTableModel(rs));
            
            String sql1 = "select * from music_info";
            PreparedStatement pstmt1 = conn.prepareStatement(sql1);
            ResultSet rs1 = pstmt1.executeQuery();
            jt_musicData.setModel(DbUtils.resultSetToTableModel(rs1));
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantityHolder = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        button5 = new java.awt.Button();
        txtBookTitle = new javax.swing.JTextField();
        txtBookAuthor = new javax.swing.JTextField();
        txtBookSubject = new javax.swing.JTextField();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_bookData = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_Withdraw = new java.awt.Button();
        user_fullName = new javax.swing.JLabel();
        adminTxtIDLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_musicData = new javax.swing.JTable();
        txtGenre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        button_Withdraw1 = new java.awt.Button();
        txtQuantityMusic = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSongID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        button_LookupSong = new java.awt.Button();
        txtAlbumTitle = new javax.swing.JTextField();
        txtArtist = new javax.swing.JTextField();
        button_Checkout = new java.awt.Button();

        quantityHolder.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Book Title: ");

        jLabel5.setText("Book ID:");

        jLabel2.setText("Author:");

        txtBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Subject: ");

        button5.setLabel("Lookup BookID");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        txtBookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookTitleActionPerformed(evt);
            }
        });

        txtBookAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookAuthorActionPerformed(evt);
            }
        });

        txtBookSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookSubjectActionPerformed(evt);
            }
        });

        button2.setLabel("Refresh");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setLabel("Logout");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        jt_bookData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jt_bookData);

        jLabel4.setText("Quantity: ");

        jLabel6.setText("Withdraw Book by entering Book ID");

        button_Withdraw.setLabel("Withdraw");
        button_Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_WithdrawActionPerformed(evt);
            }
        });

        user_fullName.setText("jLabel71");

        adminTxtIDLabel.setForeground(new java.awt.Color(60, 63, 65));
        adminTxtIDLabel.setText("jLabel7");

        jt_musicData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_musicData);

        txtGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenreActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantity: ");

        jLabel8.setText("Withdraw Album by entering Song ID");

        button_Withdraw1.setLabel("Withdraw");
        button_Withdraw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Withdraw1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Album Title:");

        jLabel10.setText("Song ID:");

        jLabel11.setText("Artist::");

        txtSongID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSongIDActionPerformed(evt);
            }
        });

        jLabel12.setText("Genre:");

        button_LookupSong.setActionCommand("Lookup SongID");
        button_LookupSong.setLabel("Lookup SongID");
        button_LookupSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LookupSongActionPerformed(evt);
            }
        });

        txtAlbumTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlbumTitleActionPerformed(evt);
            }
        });

        txtArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistActionPerformed(evt);
            }
        });

        button_Checkout.setLabel("List of Withdrawals");
        button_Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user_fullName)
                        .addGap(364, 364, 364)
                        .addComponent(adminTxtIDLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBookSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel6))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(button_Checkout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAlbumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantityMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtSongID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(button_LookupSong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_Withdraw1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(user_fullName))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(adminTxtIDLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtBookSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(button_Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(button_Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSongID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtAlbumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_LookupSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantityMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(button_Withdraw1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookIDActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql:///customerstuff","root","And98rew");
            String sql = "select * from book_info where book_id = ?";
            int bID = Integer.parseInt(txtBookID.getText());
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, bID);
            
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                txtBookTitle.setText(rs.getString("book_title"));
                txtBookAuthor.setText(rs.getString("book_author"));
                txtBookSubject.setText(rs.getString("subject"));
                txtQuantity.setText(rs.getString("quantity"));
            }
            else {
                JOptionPane.showMessageDialog(null, "Record not found");
                	System.out.println(dtf.format(localDate)); //2016/11/16
            }

            conn.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void txtBookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookTitleActionPerformed

    private void txtBookAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookAuthorActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        DisplayTable();
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        new UserLogin().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_button3ActionPerformed

    private void button_WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_WithdrawActionPerformed
        // TODO add your handling code here://////////////

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql:///customerstuff","root","And98rew");

            
            String sql = "update book_info set quantity = ? where book_id = ?";
            
            String textQ = txtQuantity.getText();
            int n = Integer.parseInt(textQ);
            String x = txtBookID.getText();

            if (n > 0) {
            n = n - 1;
            PreparedStatement pstmt = conn.prepareStatement(sql);
            
            pstmt.setInt(1, n);
            pstmt.setString(2, x);
            
            
            
            
            //i = i + 1;
            //String sql1 = "update user_info set quantity = ?";
            //PreparedStatement pstmt1 = conn.prepareStatement(sql1);
            //pstmt1.setInt(1, i);

            
            String sql1 = "update user_info set quantity = quantity + 1 where id = ?";
            
            //int ID = adminTxtIDLabel.getText();
            String ID = adminTxtIDLabel.getText();
            int ID1 = Integer.parseInt(ID);
            //System.out.print(ID1);
            PreparedStatement pstmt1 = conn.prepareStatement(sql1);
            //int i = Integer.parseInt("quantity");
            //i = i + 1;
            /////////pstmt1.setInt(1, );
            pstmt1.setInt(1, ID1);
            
            if (count == 0){
            String sql2 = "update rent_info set bookID = ?, rentDate = curDate(), rentDue = curDate() + Interval 1 week, currentDate = curDate() where userID = ?";
            	//System.out.println(dtf.format(localDate)); //2016/11/16
            
            PreparedStatement pstmt2 = conn.prepareStatement(sql2);
            pstmt2.setString(1,x);
            pstmt2.setInt(2,ID1);
            pstmt2.executeUpdate();

            }
            if (count == 1) {
            String sql2 = "update rent_info set bookID1 = ?, rentDate = curDate(), rentDue = curDate() + Interval 1 week, currentDate = curDate() where userID = ?";
            
            PreparedStatement pstmt2 = conn.prepareStatement(sql2);
            pstmt2.setString(1,x);
            pstmt2.setInt(2,ID1);
            pstmt2.executeUpdate();

            }
            if (count == 2) {
            String sql2 = "update rent_info set bookID2 = ?, rentDate = curDate(), rentDue = curDate() + Interval 1 week, currentDate = curDate() where userID = ?";
            
            PreparedStatement pstmt2 = conn.prepareStatement(sql2);
            pstmt2.setString(1,x);
            pstmt2.setInt(2,ID1);
            pstmt2.executeUpdate();

            }
            if (count >= 3)
            {
                JOptionPane.showMessageDialog(null, "You have now rented too many books please return at least one");
                    String userID = adminTxtIDLabel.getText();
                    int userID1 = Integer.parseInt(userID);
                    
                    new itemsDue(userID1).setVisible(true);
                    setVisible(false);
            }
            
            //String textUserQ = // set value equal to quantity of user with name $userFullName;
            pstmt.executeUpdate();
            pstmt1.executeUpdate();
            DisplayTable();
            if (count <= 2){
            JOptionPane.showMessageDialog(null, "Information Updated Successfully");
            count = count + 1;
            System.out.println(count);
            }
            
            conn.close();
        }
            else {
                JOptionPane.showMessageDialog(null, "That book is currently unavailable");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_button_WithdrawActionPerformed

    private void txtBookSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookSubjectActionPerformed

    private void txtGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenreActionPerformed

    private void button_Withdraw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Withdraw1ActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql:///customerstuff","root","And98rew");
            String sql = "update music_info set quantity = ? where song_ID = ?";
            
            String songQ = txtQuantityMusic.getText();
            int n = Integer.parseInt(songQ);
            String x = txtSongID.getText();
            if (n > 0) {
            n = n - 1;
            PreparedStatement pstmt = conn.prepareStatement(sql);
            
            pstmt.setInt(1, n);
            pstmt.setString(2, x);
            
            
            
            
            //i = i + 1;
            //String sql1 = "update user_info set quantity = ?";
            //PreparedStatement pstmt1 = conn.prepareStatement(sql1);
            //pstmt1.setInt(1, i);
            
            String sql1 = "update user_info set quantity = quantity + 1 where id = ?";
            
            //int ID = adminTxtIDLabel.getText();
            String ID = adminTxtIDLabel.getText();
            int ID1 = Integer.parseInt(ID);
            //System.out.print(ID1);
            PreparedStatement pstmt1 = conn.prepareStatement(sql1);
            //int i = Integer.parseInt("quantity");
            //i = i + 1;
            /////////pstmt1.setInt(1, );
            pstmt1.setInt(1, ID1);
            //String textUserQ = // set value equal to quantity of user with name $userFullName;
            pstmt.executeUpdate();
            pstmt1.executeUpdate();
            DisplayTable();
            JOptionPane.showMessageDialog(null, "Information Updated Successfully");
            
            conn.close();
        }
            else {
                JOptionPane.showMessageDialog(null, "That album is currently unavailable");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_button_Withdraw1ActionPerformed

    private void txtSongIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSongIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSongIDActionPerformed

    private void button_LookupSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LookupSongActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql:///customerstuff","root","And98rew");
            String sql = "select * from music_info where song_ID = ?";

            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, Integer.parseInt(txtSongID.getText()));

            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                txtAlbumTitle.setText(rs.getString("albumTitle"));
                txtArtist.setText(rs.getString("artist"));
                txtGenre.setText(rs.getString("genre"));
                txtQuantityMusic.setText(rs.getString("quantity"));
            }
            else {
                JOptionPane.showMessageDialog(null, "Record (get it haha) not found");
            }

            conn.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_button_LookupSongActionPerformed

    private void txtAlbumTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlbumTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlbumTitleActionPerformed

    private void txtArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistActionPerformed

    private void button_CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CheckoutActionPerformed
        // TODO add your handling code here:
                    String ID = adminTxtIDLabel.getText();
                    int ID1 = Integer.parseInt(ID);
                    
                    new itemsDue(ID1).setVisible(true);
                    setVisible(false);
    }//GEN-LAST:event_button_CheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserBookshelf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserBookshelf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserBookshelf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserBookshelf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserBookshelf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminTxtIDLabel;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button5;
    private java.awt.Button button_Checkout;
    private java.awt.Button button_LookupSong;
    private java.awt.Button button_Withdraw;
    private java.awt.Button button_Withdraw1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jt_bookData;
    private javax.swing.JTable jt_musicData;
    private javax.swing.JLabel quantityHolder;
    private javax.swing.JTextField txtAlbumTitle;
    private javax.swing.JTextField txtArtist;
    private javax.swing.JTextField txtBookAuthor;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtBookSubject;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQuantityMusic;
    private javax.swing.JTextField txtSongID;
    private javax.swing.JLabel user_fullName;
    // End of variables declaration//GEN-END:variables
}
